### ISSUE TITLE
Unable to add preview version

### ISSUE THREAD

**Issue by itobby** [JannikLassahn/graphql-dotnet-upload#10]
Hi,
I am trying to add the preview version as I am using net core 3.1.
May you kindly assist.
```info :   CACHE https://api.nuget.org/v3-flatcontainer/graphql.upload.aspnetcore/index.json
error: Unable to find package GraphQL.Upload.AspNetCore with version (>= 1.0.0-preview-2)
error:   - Found 5 version(s) in nuget.org [ Nearest version: 0.4.0 ]

**Comment by JannikLassahn** [comment]
The preview versions are only available via GitHub. I am not uploading them to Nuget yet because the master-branch version is still listed as preview version and adding another preview from the develop-branch might be confusing.

If you are using the dotnet CLI you can easily add the package by adding a new nuget source
`dotnet nuget add source https://nuget.pkg.github.com/janniklassahn/index.json -n github -u <USERNAME> -p <PASSWORD_OR_TOKEN> --store-password-in-clear-text` (see [CLI docs](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-add-source)) and running  `dotnet add package GraphQL.Upload.AspNetCore -v 1.0.0-preview-2`  in your project

See [GitHub docs](https://help.github.com/en/packages/using-github-packages-with-your-projects-ecosystem/configuring-dotnet-cli-for-use-with-github-packages#authenticating-to-github-packages) for different ways to consume a package hosted on GitHub.

**Comment by itobby** [comment]
Ok got it. Much thanks.
